In [68]:
import pandas as pd
import numpy as np

In [69]:
#file_paths
ss_file_path = "data/Names for Generator - Scottish Surnames.csv"
sf_file_path = "data/Names for Generator - Scottish Fornames.csv"
uss_file_path = "data/Names for Generator - US Census Surnames.csv"
usf_file_path = "data/Names for Generator - US Census Forenames.csv"

In [70]:
scottish_surnames = pd.read_csv(ss_file_path)

scottish_forenames = pd.read_csv(sf_file_path)

us_surnames = pd.read_csv(uss_file_path)

us_forenames =pd.read_csv(usf_file_path)

Reworking Scottish Surnames

In [71]:
scottish_surnames.drop(columns=["Year", "Rank", "Number"], inplace=True)
scottish_surnames.head()

    Surname
0     Smith
1     Brown
2    Wilson
3   Thomson
4  Campbell

Reworking US surnames

In [72]:
us_surnames.drop(columns=["RANK"], inplace=True)
us_surnames.columns = ["Surname"]
us_surnames["Surname"] = us_surnames["Surname"].str.capitalize()
us_surnames.head()

    Surname
0     Smith
1   Johnson
2  Williams
3     Brown
4     Jones

Combining DataFrames dropping common surnames

In [73]:
surnames = pd.concat([us_surnames, scottish_surnames]).drop_duplicates().reset_index(drop=True)
surnames.head()

    Surname
0     Smith
1   Johnson
2  Williams
3     Brown
4     Jones

In [74]:
#checking if it worked
did_it_work = (len(scottish_surnames) + len(us_surnames)) != len(surnames)
print(did_it_work)

True

Reworking Scottish Forenames

In [75]:
scottish_forenames.head()

,Sex,Name,Number in 2025,Rank in 2025,Rank in 2024,Rank in 2010s,Rank in 2000s,Rank in 1990s,Rank in 1980s,Rank in 1970s,Change in Ranking 2024-2025
0,Boy,Noah,318,1,1,12,112,475,1108,934,0
1,Boy,Luca,302,2,6,85,140,383,623,763,4
2,Boy,Rory,301,3,3,24,57,69,94,105,0
3,Boy,Muhammad,291,4,2,55,121,189,194,233,-2
4,Boy,Oliver,269,5,7,4,53,120,124,147,2

In [76]:
scottish_forenames.drop(columns=["Number in 2025", "Rank in 2025", "Rank in 2024", "Rank in 2010s", "Rank in 2000s", "Rank in 1990s", "Rank in 1980s", "Rank in 1970s", "Change in Ranking 2024-2025"], inplace=True)
scottish_forenames.head()

   Sex      Name
0  Boy      Noah
1  Boy      Luca
2  Boy      Rory
3  Boy  Muhammad
4  Boy    Oliver

In [77]:
# splitting by gender
scottish_forenames_boy = scottish_forenames[scottish_forenames["Sex"] == "Boy"]
scottish_forenames_girl = scottish_forenames[scottish_forenames["Sex"] == "Girl"]

Reworking US Forenames

In [78]:
us_forenames.head()

,FIRST NAME,RANK,FREQUENCY (COUNT),"PROPORTION PER 100,000 POPULATION",CUMULATIVE PROPORTION,MALE,FEMALE
0,MICHAEL,1,"3,476,721","1,151.11","1,151.11","3,469,434","7,287"
1,JOHN,2,"3,125,123","1,034.70","2,185.81","3,118,620","6,503"
2,JAMES,3,"2,996,421",992.09,"3,177.90","2,992,500","3,921"
3,DAVID,4,"2,813,017",931.37,"4,109.27","2,810,463","2,554"
4,ROBERT,5,"2,759,339",913.59,"5,022.86","2,756,604","2,735"

In [79]:
us_forenames.drop(columns=["FREQUENCY (COUNT)", "PROPORTION PER 100,000 POPULATION", "CUMULATIVE PROPORTION"], inplace=True)
us_forenames.head()

  FIRST NAME RANK       MALE FEMALE
0    MICHAEL    1  3,469,434  7,287
1       JOHN    2  3,118,620  6,503
2      JAMES    3  2,992,500  3,921
3      DAVID    4  2,810,463  2,554
4     ROBERT    5  2,756,604  2,735

In [80]:
# changing to float64 type
us_forenames["MALE"] = pd.to_numeric(us_forenames["MALE"].astype(str).str.replace(",", ""))
us_forenames["FEMALE"] = pd.to_numeric(us_forenames["FEMALE"].astype(str).str.replace(",", ""))

In [81]:
# adding boy/girl column
us_forenames['Sex'] = np.where(us_forenames["MALE"] >= us_forenames["FEMALE"], "Boy", "Girl")
us_forenames.head()

  FIRST NAME RANK     MALE  FEMALE  Sex
0    MICHAEL    1  3469434    7287  Boy
1       JOHN    2  3118620    6503  Boy
2      JAMES    3  2992500    3921  Boy
3      DAVID    4  2810463    2554  Boy
4     ROBERT    5  2756604    2735  Boy

In [82]:
us_forenames.drop(columns=["MALE", "FEMALE", "RANK"], inplace=True)

In [83]:
us_forenames.columns = ["Name", "Sex"]
us_forenames.head()

      Name  Sex
0  MICHAEL  Boy
1     JOHN  Boy
2    JAMES  Boy
3    DAVID  Boy
4   ROBERT  Boy

In [84]:
us_forenames["Name"] = us_forenames["Name"].str.capitalize()
us_forenames.head()

      Name  Sex
0  Michael  Boy
1     John  Boy
2    James  Boy
3    David  Boy
4   Robert  Boy

In [85]:
us_forenames = us_forenames[["Sex", "Name"]]

In [86]:
us_forenames_boy = us_forenames[us_forenames["Sex"] == "Boy"]
us_forenames_girl = us_forenames[us_forenames["Sex"] == "Girl"]

In [87]:
us_forenames_boy.head()

   Sex     Name
0  Boy  Michael
1  Boy     John
2  Boy    James
3  Boy    David
4  Boy   Robert

In [88]:
forenames_boy = pd.concat([us_forenames_boy, scottish_forenames_boy]).drop_duplicates().reset_index(drop=True)
forenames_girl = pd.concat([us_forenames_girl, scottish_forenames_girl]).drop_duplicates().reset_index(drop=True)
forenames_boy.head()

   Sex     Name
0  Boy  Michael
1  Boy     John
2  Boy    James
3  Boy    David
4  Boy   Robert

In [90]:
did_it_work = (len(scottish_forenames_girl) + len(us_forenames_girl)) != len(forenames_girl)
print(did_it_work)

True

In [93]:
surnames.to_csv("cleaned_data/surnames.csv")
forenames_boy.to_csv("cleaned_data/forenames_boy.csv")
forenames_girl.to_csv("cleaned_data/forenames_girl.csv")